CREATE TABLE IF NOT EXISTS employees (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    department VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW()
);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS salary NUMERIC(10,2);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS position VARCHAR(50);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS likings VARCHAR(50);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS bonus VARCHAR(50);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS height VARCHAR(50);

